import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:shohoj/core/gpa.dart';
import 'package:shohoj/models/course.dart';
import 'package:shohoj/models/semester.dart';

/// Differential test against the web app's real implementation.
///
/// `test/oracle_fixture.json` is generated by running the same fixtures through
/// `js/core/gpa-core.js` in Node — see the PR for the script. It pins this port
/// to the reference implementation rather than to my reading of it.
///
/// Regenerate whenever the web's algorithm changes; a diff here means the two
/// clients would show different CGPAs for the same transcript.
Course c(String name, double credits, String grade) =>
    Course(name: name, credits: credits, grade: grade);

Semester s(int id, List<Course> courses, {bool running = false}) =>
    Semester(id: id, name: 'S$id', courses: courses, running: running);

Semester summary(int id, double cgpa, double credits, double attempted) => Semester(
      id: id,
      courses: const [],
      summary: true,
      summaryCGPA: cgpa,
      summaryCredits: credits,
      summaryAttempted: attempted,
    );

final cases = <String, List<Semester>>{
  'retake_latest': [s(0, [c('X (CSE111)', 3, 'F')]), s(1, [c('X (CSE111)', 3, 'A')])],
  'retake_best': [s(0, [c('X (CSE111)', 3, 'A')]), s(1, [c('X (CSE111)', 3, 'C')])],
  'fnt_retaken': [
    s(0, [c('Programming Language I (CSE110)', 3, 'C-')]),
    s(1, [c('Programming Language II (CSE111)', 3, 'F(NT)')]),
    s(2, [c('Programming Language II (CSE111)', 3, 'B')]),
  ],
  'withdrawal': [s(0, [c('X (CSE111)', 3, 'A'), c('Y (CSE112)', 3, 'W')])],
  'w_no_supersede': [s(0, [c('X (CSE111)', 3, 'A')]), s(1, [c('X (CSE111)', 3, 'W')])],
  'running': [s(0, [c('A (X100)', 3, 'C')]), s(1, [c('B (X101)', 3, 'A')], running: true)],
  'summary': [summary(0, 3.0, 30, 30), s(1, [c('A (X100)', 3, 'A')])],
  'summary_att': [summary(0, 3.0, 30, 36)],
  'pass_incomplete': [
    s(0, [c('A (X100)', 3, 'A'), c('B (X101)', 0, 'P'), c('C (X102)', 3, 'I')])
  ],
  'three_attempts': [
    s(0, [c('X (CSE111)', 3, 'F')]),
    s(1, [c('X (CSE111)', 3, 'C')]),
    s(2, [c('X (CSE111)', 3, 'A')]),
  ],
  'fail_only': [s(0, [c('A (X100)', 3, 'A'), c('B (X101)', 3, 'F')])],
};

const policies = {
  'fall2024': ('Fall', '2024'),
  'spring2023': ('Spring', '2023'),
};

void main() {
  late Map<String, dynamic> oracle;

  setUpAll(() {
    oracle = jsonDecode(File('test/oracle_fixture.json').readAsStringSync())
        as Map<String, dynamic>;
  });

  test('every fixture in the oracle is exercised', () {
    expect(oracle.keys.length, cases.length * policies.length);
  });

  for (final caseEntry in cases.entries) {
    for (final policyEntry in policies.entries) {
      final key = '${caseEntry.key}|${policyEntry.key}';

      test('matches the web: $key', () {
        final (season, year) = policyEntry.value;
        final t = calculateCgpaTotals(
          caseEntry.value,
          startSeason: season,
          startYear: year,
        );
        final want = oracle[key] as Map<String, dynamic>;

        final wantCgpa = want['cgpa'];
        if (wantCgpa == null) {
          expect(t.cgpa, isNull);
        } else {
          expect(t.cgpa, closeTo((wantCgpa as num).toDouble(), 0.000001));
        }
        expect(t.cgpaCredits, (want['cgpaCredits'] as num).toDouble());
        expect(t.attemptedCredits, (want['attempted'] as num).toDouble());
        expect(t.earnedCredits, (want['earned'] as num).toDouble());
      });
    }
  }
}
