// Generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
// This file will be replaced by the actual generated one.
// DO NOT edit manually — run flutterfire configure instead.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform for Shohoj.');
    }
  }

  // ── Replace these values after running: flutterfire configure ────────────
  // Your Firebase project ID is: shohoj

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4cz0TPyvqgeZicrsX5bEgxIJuGlour54',
    authDomain: 'shohoj.firebaseapp.com',
    projectId: 'shohoj',
    storageBucket: 'shohoj.firebasestorage.app',
    messagingSenderId: '878391653144',
    appId: '1:878391653144:web:172ccb90535dfd48d9a46d',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhwAiCHz8NmSYFAVM__f3jMIHnAfy278',
    appId: '1:878391653144:android:fe15e2c9d3d7b84ed9a46d',
    messagingSenderId: '878391653144',
    projectId: 'shohoj',
    storageBucket: 'shohoj.firebasestorage.app',
  );

  // ── Android & iOS: add after running flutterfire configure ───────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5O8jhquGt3KbVZLjA6MJsstoWo6cukA',
    appId: '1:878391653144:ios:6a39b4eb3a7f8fc5d9a46d',
    messagingSenderId: '878391653144',
    projectId: 'shohoj',
    storageBucket: 'shohoj.firebasestorage.app',
    iosClientId: '878391653144-ts2q0pttkkpefmu9arb1sd1k3744j75b.apps.googleusercontent.com',
    iosBundleId: 'com.shohoj.shohojApp',
  );

}